---
name: "Build & Test"
on:  # yamllint disable-line rule:truthy
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
jobs:
  unit:
    name: "Unit"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v6"
      - uses: "authzed/actions/setup-go@main"
      - uses: "authzed/actions/go-test@main"
